use crate::models::PairingCode;
/// Pairing: short human-readable code that embeds the iroh EndpointAddr.
/// Format: XXXX-XXXX:<base64-encoded EndpointAddr JSON>
/// The short code part is for display; the full string is what gets exchanged.
use anyhow::Result;
use base32::Alphabet;
use base64::Engine as _;
use chrono::{Duration, Utc};
use rand::Rng;
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The portable portion of a pairing code.  A code is deliberately
/// self-contained because the two devices do not share a SQLite database.
#[derive(Debug, Serialize, Deserialize)]
struct PairingTicket {
    version: u8,
    endpoint_addr: String,
    expires_at: String,
}

/// Generate a pairing code that embeds the endpoint addr for direct dialing.
/// `endpoint_addr_json` is the serialized iroh EndpointAddr (or empty string
/// if iroh hasn't started yet — the short code still works for manual entry).
pub fn generate_pairing_code(
    conn: &Connection,
    endpoint_addr_json: Option<&str>,
) -> Result<PairingCode> {
    let mut rng = rand::thread_rng();
    let bytes: Vec<u8> = (0..5).map(|_| rng.gen::<u8>()).collect();
    let encoded = base32::encode(Alphabet::RFC4648 { padding: false }, &bytes);
    let short = format!("{}-{}", &encoded[..4], &encoded[4..8]);

    let id = Uuid::new_v4().to_string();
    let created_at = Utc::now().to_rfc3339();
    let expires_at = (Utc::now() + Duration::minutes(15)).to_rfc3339();

    // Full code is self-contained so it can be consumed on a different PC.
    // The expiry travels with the ticket; a receiver must never rely on its
    // own local pairing_codes table to validate a remote ticket.
    let full_code = if let Some(addr) = endpoint_addr_json.filter(|s| !s.is_empty()) {
        let ticket = PairingTicket {
            version: 1,
            endpoint_addr: addr.to_string(),
            expires_at: expires_at.clone(),
        };
        let encoded = serde_json::to_vec(&ticket)?;
        let b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(encoded);
        format!("{}:{}", short, b64)
    } else {
        short.clone()
    };

    conn.execute(
        "INSERT INTO pairing_codes (id, code, created_at, expires_at, used) VALUES (?1, ?2, ?3, ?4, 0)",
        rusqlite::params![id, full_code, created_at, expires_at],
    )?;

    Ok(PairingCode {
        id,
        code: full_code,
        created_at,
        expires_at,
    })
}

/// Parse a pairing code entered by the user.
/// Returns (short_display_code, Option<endpoint_addr_json>)
pub fn parse_pairing_code(code: &str) -> (String, Option<String>) {
    let code = code.trim();
    if let Some(colon_pos) = code.find(':') {
        let short = code[..colon_pos].to_string();
        let b64 = &code[colon_pos + 1..];
        let addr = base64::engine::general_purpose::STANDARD
            .decode(b64)
            .ok()
            .and_then(|b| String::from_utf8(b).ok());
        (short, addr)
    } else {
        (code.to_string(), None)
    }
}

/// Decode a full cross-device ticket and enforce the expiry embedded in it.
/// The legacy raw EndpointAddr form remains readable for existing codes
/// generated by earlier app versions, but newly generated tickets always use
/// the versioned, expiring form above.
fn decode_remote_ticket(code: &str) -> Result<String> {
    let (_, encoded) = code
        .split_once(':')
        .ok_or_else(|| anyhow::anyhow!("Enter the full connection code from the other device"))?;
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(encoded)
        .or_else(|_| base64::engine::general_purpose::STANDARD.decode(encoded))
        .map_err(|_| anyhow::anyhow!("The connection code is malformed"))?;

    if let Ok(ticket) = serde_json::from_slice::<PairingTicket>(&bytes) {
        if ticket.version != 1 || ticket.endpoint_addr.trim().is_empty() {
            return Err(anyhow::anyhow!("The connection code is invalid"));
        }
        let expires_at = chrono::DateTime::parse_from_rfc3339(&ticket.expires_at)
            .map_err(|_| anyhow::anyhow!("The connection code has an invalid expiry"))?;
        if expires_at <= Utc::now() {
            return Err(anyhow::anyhow!(
                "This connection code has expired. Generate a new one."
            ));
        }
        return Ok(ticket.endpoint_addr);
    }

    // Compatibility with codes made before versioned pairing tickets.  They
    // cannot carry an expiry, so only accept a valid UTF-8 EndpointAddr JSON.
    String::from_utf8(bytes).map_err(|_| anyhow::anyhow!("The connection code is malformed"))
}

/// Validate and consume a pairing code. Returns the embedded endpoint addr if present.
pub fn consume_pairing_code(conn: &Connection, code: &str) -> Result<Option<String>> {
    let now = Utc::now().to_rfc3339();

    // A complete code came from another device.  It is not (and cannot be)
    // present in this device's database.  Treat it as a portable ticket.
    if code.trim().contains(':') {
        return decode_remote_ticket(code.trim()).map(Some);
    }

    // Match on the full code string
    let rows = conn.execute(
        "UPDATE pairing_codes SET used = 1 WHERE code = ?1 AND used = 0 AND expires_at > ?2",
        rusqlite::params![code, now],
    )?;

    if rows == 0 {
        // Also try matching just the short prefix (user may have typed only XXXX-XXXX)
        let short = code.split(':').next().unwrap_or(code);
        let full: Option<String> = conn.query_row(
            "SELECT code FROM pairing_codes WHERE code LIKE ?1 AND used = 0 AND expires_at > ?2 LIMIT 1",
            rusqlite::params![format!("{}%", short), now],
            |row| row.get(0),
        ).ok();

        if let Some(ref full_code) = full {
            conn.execute(
                "UPDATE pairing_codes SET used = 1 WHERE code = ?1",
                rusqlite::params![full_code],
            )?;
            let (_, embedded) = parse_pairing_code(full_code);
            return Ok(embedded);
        }
        return Err(anyhow::anyhow!("Code not found, already used, or expired"));
    }

    Ok(None)
}

/// Get the cryptographically authenticated iroh endpoint ID from a ticket.
pub fn endpoint_node_id(endpoint_addr_json: &str) -> Result<String> {
    let addr: iroh::EndpointAddr = serde_json::from_str(endpoint_addr_json)
        .map_err(|e| anyhow::anyhow!("Invalid endpoint address in connection code: {e}"))?;
    Ok(addr.id.to_string())
}

/// Store the refreshed endpoint addr for a peer (called after each successful connection)
pub fn update_peer_endpoint(
    conn: &Connection,
    node_id: &str,
    endpoint_addr_json: &str,
) -> Result<()> {
    let last_seen = Utc::now().to_rfc3339();
    conn.execute(
        "UPDATE peers SET endpoint_addr = ?1, last_seen = ?2, is_online = 1 WHERE node_id = ?3",
        rusqlite::params![endpoint_addr_json, last_seen, node_id],
    )?;
    Ok(())
}

/// Get all peers that have a stored endpoint addr (for auto-reconnect on startup)
pub fn get_reconnectable_peers(conn: &Connection) -> Result<Vec<(String, String)>> {
    let mut stmt = conn.prepare(
        "SELECT node_id, endpoint_addr FROM peers WHERE endpoint_addr IS NOT NULL AND endpoint_addr != ''"
    )?;
    let peers = stmt
        .query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })?
        .filter_map(|r| r.ok())
        .collect();
    Ok(peers)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn db() -> Connection {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch("CREATE TABLE pairing_codes (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, used INTEGER NOT NULL DEFAULT 0);").unwrap();
        conn
    }

    #[test]
    fn a_full_ticket_is_consumed_without_a_local_database_row() {
        let issuer = db();
        let code =
            generate_pairing_code(&issuer, Some(r#"{\"id\":\"example\",\"addrs\":[]}"#)).unwrap();
        let receiver = db();
        assert_eq!(
            consume_pairing_code(&receiver, &code.code).unwrap(),
            Some(r#"{\"id\":\"example\",\"addrs\":[]}"#.to_string())
        );
    }

    #[test]
    fn expired_portable_ticket_is_rejected() {
        let ticket = PairingTicket {
            version: 1,
            endpoint_addr: "{}".into(),
            expires_at: (Utc::now() - Duration::minutes(1)).to_rfc3339(),
        };
        let encoded = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .encode(serde_json::to_vec(&ticket).unwrap());
        assert!(consume_pairing_code(&db(), &format!("ABCD-EFGH:{encoded}")).is_err());
    }
}
